<a href="https://colab.research.google.com/github/ramesitexp/DataScience_Zone/blob/main/logistics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
import joblib

In [ ]:
x,y = make_classification(n_samples=1000, n_features=4, n_informative=3, n_redundant=1, random_state=42 , n_classes=2)

In [ ]:
x

array([[ 0.98083161,  0.40841039,  1.16809813, -0.12357109],
       [ 0.44527728, -1.98619811,  0.21974397,  1.86935094],
       [-1.89222477, -1.03217141,  1.54176061, -0.1757323 ],
       ...,
       [-0.36820117, -1.60251526, -0.45685167,  1.30021259],
       [ 0.47022793, -2.73756477, -0.47538663,  2.64303567],
       [ 1.24346122, -1.4593113 ,  1.46814536,  1.55185137]],
      shape=(1000, 4))

In [ ]:
y

array([1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,

In [ ]:
df = pd.DataFrame(x,columns=["hours studies","mock_test","attendence","practice_score"])

In [ ]:
df

hours studies  mock_test  attendence  practice_score
0         0.980832   0.408410    1.168098       -0.123571
1         0.445277  -1.986198    0.219744        1.869351
2        -1.892225  -1.032171    1.541761       -0.175732
3         0.081571  -2.216266   -0.718966        2.066282
4         1.454131   0.605897    0.629691       -0.002079
..             ...        ...         ...             ...
995      -1.062780  -1.599082   -1.973174        1.248611
996      -0.982087  -0.767210    0.357611        0.181480
997      -0.368201  -1.602515   -0.456852        1.300213
998       0.470228  -2.737565   -0.475387        2.643036
999       1.243461  -1.459311    1.468145        1.551851

[1000 rows x 4 columns]

In [ ]:
y

array([1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,

In [ ]:
df["target"] = y

In [ ]:
df

hours studies  mock_test  attendence  practice_score  target
0         0.980832   0.408410    1.168098       -0.123571       1
1         0.445277  -1.986198    0.219744        1.869351       0
2        -1.892225  -1.032171    1.541761       -0.175732       0
3         0.081571  -2.216266   -0.718966        2.066282       0
4         1.454131   0.605897    0.629691       -0.002079       1
..             ...        ...         ...             ...     ...
995      -1.062780  -1.599082   -1.973174        1.248611       0
996      -0.982087  -0.767210    0.357611        0.181480       0
997      -0.368201  -1.602515   -0.456852        1.300213       0
998       0.470228  -2.737565   -0.475387        2.643036       0
999       1.243461  -1.459311    1.468145        1.551851       1

[1000 rows x 5 columns]

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(df[["hours studies","mock_test","attendence","practice_score"]],df["target"],test_size=0.2,random_state=42)

In [ ]:
model = Pipeline(steps=[('scaler', StandardScaler()), ('logistic_regression', LogisticRegression(solver='lbfgs',max_iter=1000,verbose=0))])

In [ ]:
model.fit(x_train,y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('logistic_regression', LogisticRegression(max_iter=1000))])

In [ ]:
model.predict(x_test)

array([0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 1])

In [ ]:
y_test

521    1
737    0
740    0
660    0
411    0
      ..
408    1
332    1
208    0
613    0
78     1
Name: target, Length: 200, dtype: int64

In [ ]:
accuracy_score(y_test,model.predict(x_test))

0.865

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix

In [ ]:
confusion_matrix(y_test,model.predict(x_test))

array([[96, 10],
       [17, 77]])

In [ ]:
print(classification_report(y_test,model.predict(x_test)))

              precision    recall  f1-score   support

           0       0.85      0.91      0.88       106
           1       0.89      0.82      0.85        94

    accuracy                           0.86       200
   macro avg       0.87      0.86      0.86       200
weighted avg       0.87      0.86      0.86       200

