<a href="https://colab.research.google.com/github/ramesitexp/DataScience_Zone/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [7]:
a=10,5
type(a)

tuple

In [8]:
a1=np.array(a)

In [9]:
a1.ndim

1

In [10]:
a2=np.array([[1,2,3,4],[2,4,9,16],[4,8,18,32]])

In [11]:
a2.ndim

2

In [12]:
np.array([9,8,7,6]).ndim

1

In [13]:
a3=np.array([[[1,2,3,4],[2,4,9,16],[4,8,18,32]],[[1,2,3,4],[2,4,9,16],[4,8,18,32]]])
a3.ndim

3

In [19]:
emptyArray=np.empty((4,2))
print(emptyArray)

[[7.69226145e-316 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]


In [25]:
ones=np.ones((4,3,4),dtype=int)
print(ones)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [27]:
zeros=np.zeros((5,3,4),dtype=np.int16)
print(zeros)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [32]:
s=np.random.random((2,2,2))
print(s)

[[[0.9137348  0.6243444 ]
  [0.55240284 0.46880657]]

 [[0.09570695 0.363208  ]
  [0.75125829 0.31329124]]]


In [35]:
fullArray=np.full((2,2),9.2)

In [36]:
print(fullArray)

[[9.2 9.2]
 [9.2 9.2]]


In [38]:
evenspaceArray=np.arange(0,26,5)
print(evenspaceArray)

[ 0  5 10 15 20 25]


In [40]:
evenSpacedArray2=np.linspace(0,2,99)
print(evenSpacedArray2)

[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.         1.02040816 1.04081633 1.06122449 1.08163265
 1.10204082 1.12244898 1.14285714 1.16326531 1.18367347 1.20408163
 1.2244898  1.24489796 1.26530612 1.28571429 1.30612245 1.32653061
 1.34693878 1.36734694 1.3877551  1.40816327 1.42857143 1.44897959
 1.46938776 1.48979592 1.51020408 1.53061224 1.55102041 1.57142857
 1.59183673 1.6122449  1.63265306 1.65306122 1.67346939 1.69387755
 1.71428571 1.73469388 1.75510204 1.7755102  1.79591837 1.81632

In [41]:
zeros=np.zeros((5,3,4),dtype=np.int16)
e=zeros.ravel()
print(e)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [42]:
zeros=np.zeros((5,3,4),dtype=np.int16)
e=zeros.flatten()
print(e)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [43]:
t=np.array([[5,4,33,4],[6,7,8,9],[7,5,7,9]])
t

array([[ 5,  4, 33,  4],
       [ 6,  7,  8,  9],
       [ 7,  5,  7,  9]])

In [48]:
t[:,1:3]

array([[ 4, 33],
       [ 7,  8],
       [ 5,  7]])

In [1]:
#Numpy Array Basics
# importing numpy #pip install numpy # conda install numpy
import numpy as np  # numerical python
#import array  #alias  #include<stdio.h> include <math.h>     [7,8.5,'sasi']  list , array , series ,dataframe

# Defining 1D array
my1DArray = np.array([9,8,7,6]) # row , list  #1*4 series
print(my1DArray.ndim)

# Defining and printing 2D array #vector
my2DArray = np.array([[1, 2, 3, 4], [2, 4, 9, 16], [4, 8, 18, 32]]) #
print(my2DArray.ndim)

#Defining and printing 3D array # matrix
my3Darray = np.array([[[ 1, 2 , 3 , 4],[ 5 , 6 , 7  ,8]], [[ 1,  2,  3,  4],[ 9, 10, 11, 12]]]) #
print(my3Darray.ndim)


1
2
3


In [2]:
emptyArray = np.empty((4,2))
print(emptyArray)

[[3.86585417e-315 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]


In [3]:
my3Darray

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 1,  2,  3,  4],
        [ 9, 10, 11, 12]]])

In [4]:
cv = my3Darray.ravel()
cv

array([ 1,  2,  3,  4,  5,  6,  7,  8,  1,  2,  3,  4,  9, 10, 11, 12])

In [5]:
a = np.arange(0,100,0.001) # start, end -1 , steps
a

array([0.0000e+00, 1.0000e-03, 2.0000e-03, ..., 9.9997e+01, 9.9998e+01,
       9.9999e+01])

In [7]:
b = np.linspace(1,10,20)
b

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [8]:
 v = np.random.randint(256, size=(4, 7), dtype=np.int16)
 v

array([[129, 100, 240, 157,  91, 228,  89],
       [221, 163,  36, 132, 137, 147,  59],
       [193,  36,  93,  17,  50, 167,  87],
       [215,  43,  65, 116,  80, 192,  47]], dtype=int16)

In [9]:
v[0:2,0:2] # start , end-1

array([[129, 100],
       [221, 163]], dtype=int16)

In [10]:
v[1:3,2:4]

array([[ 36, 132],
       [ 93,  17]], dtype=int16)

In [28]:
e  = np.empty(3,2)
e

TypeError: Cannot interpret '2' as a data type

In [11]:
e  = np.empty((3,2))
e

array([[0.0000e+00, 1.0000e-03],
       [2.0000e-03, 9.9997e+01],
       [9.9998e+01, 9.9999e+01]])

In [12]:
c = np.random.rand(5,10)
c

array([[0.03336307, 0.97096837, 0.28766464, 0.17596595, 0.73030179,
        0.09090128, 0.68392862, 0.72594002, 0.91404527, 0.25620997],
       [0.02831717, 0.50877644, 0.73127373, 0.23604687, 0.925383  ,
        0.94728059, 0.72391954, 0.04494791, 0.28607775, 0.91785378],
       [0.42546574, 0.34761586, 0.30956822, 0.82953145, 0.50205306,
        0.41816962, 0.02225628, 0.85897559, 0.48188954, 0.60955711],
       [0.67768735, 0.54961086, 0.3855885 , 0.8292129 , 0.63315301,
        0.84565357, 0.69265109, 0.49870156, 0.73806921, 0.00427441],
       [0.60111201, 0.5691108 , 0.28023815, 0.71629458, 0.40172687,
        0.61119224, 0.68755534, 0.94735983, 0.68084256, 0.9338283 ]])

In [13]:
c.ndim

2

In [14]:
c.shape

(5, 10)

In [15]:
c.size

50

In [16]:
c.T

array([[0.03336307, 0.02831717, 0.42546574, 0.67768735, 0.60111201],
       [0.97096837, 0.50877644, 0.34761586, 0.54961086, 0.5691108 ],
       [0.28766464, 0.73127373, 0.30956822, 0.3855885 , 0.28023815],
       [0.17596595, 0.23604687, 0.82953145, 0.8292129 , 0.71629458],
       [0.73030179, 0.925383  , 0.50205306, 0.63315301, 0.40172687],
       [0.09090128, 0.94728059, 0.41816962, 0.84565357, 0.61119224],
       [0.68392862, 0.72391954, 0.02225628, 0.69265109, 0.68755534],
       [0.72594002, 0.04494791, 0.85897559, 0.49870156, 0.94735983],
       [0.91404527, 0.28607775, 0.48188954, 0.73806921, 0.68084256],
       [0.25620997, 0.91785378, 0.60955711, 0.00427441, 0.9338283 ]])

In [17]:
c.dtype

dtype('float64')

In [18]:
c.itemsize

8

In [19]:
d = c.reshape(2,25)  # 1 *35, 35 *1 , 7 *5 , 5 *7

In [20]:
d

array([[0.03336307, 0.97096837, 0.28766464, 0.17596595, 0.73030179,
        0.09090128, 0.68392862, 0.72594002, 0.91404527, 0.25620997,
        0.02831717, 0.50877644, 0.73127373, 0.23604687, 0.925383  ,
        0.94728059, 0.72391954, 0.04494791, 0.28607775, 0.91785378,
        0.42546574, 0.34761586, 0.30956822, 0.82953145, 0.50205306],
       [0.41816962, 0.02225628, 0.85897559, 0.48188954, 0.60955711,
        0.67768735, 0.54961086, 0.3855885 , 0.8292129 , 0.63315301,
        0.84565357, 0.69265109, 0.49870156, 0.73806921, 0.00427441,
        0.60111201, 0.5691108 , 0.28023815, 0.71629458, 0.40172687,
        0.61119224, 0.68755534, 0.94735983, 0.68084256, 0.9338283 ]])

In [21]:
t = np.empty((10,3))
t.ndim

2

In [22]:
t

array([[3.98799976e-315, 0.00000000e+000, 6.01347002e-154],
       [9.52378910e+228, 1.83477254e+044, 2.35288463e+251],
       [2.06917493e+161, 3.03387744e-152, 2.31647114e-152],
       [1.01907795e+277, 9.77817447e+199, 1.39159278e-258],
       [6.01347002e-154, 9.41558777e+165, 8.70446315e+183],
       [1.27967303e-152, 6.24896858e-085, 6.01347002e-154],
       [1.14484092e+243, 5.03396122e+223, 4.65007198e-086],
       [6.01347002e-154, 4.22034703e+194, 7.27930993e+199],
       [8.01215523e-095, 3.11082252e+161, 2.31461371e-152],
       [1.63041663e-322, 6.87282855e-310, 6.87282855e-310]])

In [23]:
r = t.flatten()
r.ndim

1

In [24]:
c.ndim

2

In [25]:
s = np.array([5,7,9,9,5,6,4,7,9,8,7,6])
for i in s:
 print(i*7)

35
49
63
63
35
42
28
49
63
56
49
42


In [33]:
ss = np.array([5,7,9])
vv = np.array([8,9,7])
yy = np.array([8,7,6])

In [34]:
c = np.concatenate((ss,vv,yy))

In [35]:
c

array([5, 7, 9, 8, 9, 7, 8, 7, 6])

In [37]:
zeros = np.zeros((8,3,4),dtype=int) # 2, 50,500,578687669696  # 70, 5671253, 4   4.80 4.4567457568
print(zeros)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
