In [1]:
!pip install numpy

In [2]:
import numpy as np

In [4]:
# 1. Create a 1D Numpy array with values from 0 to 9.

arr1=np.arange(10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
#2.Create a 2D Numpy array with values with dtype=bool 
arr2=np.ones((3,3),dtype=bool)
print(arr2)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [6]:
#3. Create a Numpy array with values ranging from 10 to 49.
arr3=np.arange(10,50)
print(arr3)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [12]:
# 4. Create a 2D Numpy array and change the data type to float.
arr4=np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=float)
print(arr4)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [14]:
# 5. Create a 4x4 identity matrix.
arr5=np.identity(5)
print(arr5)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [16]:
# 6. Create a Numpy array with 10 values evenly spaced between 1 and 5.
arr6=np.linspace(1,5,10)
print(arr6)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [18]:
# 7. Create a 3x3 Numpy array with random values.
arr7=np.random.random((3,3))
print(arr7)

[[0.76255805 0.2202872  0.13706096]
 [0.0656877  0.62795033 0.72959607]
 [0.72922868 0.32751909 0.17194957]]


In [22]:
# 8. Create a Numpy array with 20 random values and reshape it to a 4x5 array.
arr8=np.random.random(20).reshape(4,5)
print(arr8)

[[0.95745396 0.93412832 0.74274701 0.42445309 0.68213855]
 [0.65400907 0.94480539 0.6935108  0.11382916 0.44276244]
 [0.59907273 0.13851034 0.90086578 0.99305878 0.42550055]
 [0.37438189 0.36977593 0.31683374 0.02768708 0.89357241]]


In [36]:
# 9. Create an array of shape (3, 3) and extract the values of the second row.
arr9=np.random.random((3,3))
second_row=arr9[1,:]
print(second_row)

[0.18431257 0.58383194 0.05236511]


In [40]:
# 10. Create a 5x5 matrix with values 1 to 25 and extract the element in the third row and fourth column.
arr10=np.arange(25).reshape(5,5)
print(arr10)
print(arr10[2,3])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
13


In [41]:
# 11. Find the shape, size, and data type of a given Numpy array.
arr11=np.arange(25).reshape(5,5)
print(arr11.shape,arr11.size,arr11.dtype)

(5, 5) 25 int32


In [44]:
# 12. Flatten a given 2D Numpy array.
arr12=np.arange(25).reshape(5,5)
flat_arr=arr12.flatten()
print(arr12)
print(flat_arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [85]:
# 13. Concatenate two Numpy arrays along the second axis.
array13_1 = np.array([[1,2],[5,1]])
array13_2 = np.array([[5, 6],[2,1]])
concatenate=np.concatenate((array13_1,array13_2),axis=1)
print(concatenate)

[[1 2 5 6]
 [5 1 2 1]]


In [74]:
# 14. Split a given Numpy array into 3 equal-sized sub-arrays.
arr14=np.arange(15).reshape(3,5)

sub_arrays=np.split(arr14,3)
print(arr14)
print(sub_arrays)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[array([[0, 1, 2, 3, 4]]), array([[5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14]])]


In [93]:
# 15. Create a Numpy array with 10 random integers between 1 and 100, and find the maximum and minimum values.
arr15=np.random.randint(1,101,size=10)
print(np.max(arr15),np.min(arr15))

92 6


In [97]:
# 16. Create a Numpy array with random values and replace all values greater than 0.5 with 1.
arr16=np.random.rand(3,3)
print(arr16)
arr16[arr16>0.5]=1
print(arr16)


[[0.65015354 0.14670484 0.27874928]
 [0.8537527  0.57013996 0.89361372]
 [0.71663717 0.73791225 0.71306768]]
[[1.         0.14670484 0.27874928]
 [1.         1.         1.        ]
 [1.         1.         1.        ]]


In [108]:
# 17. Multiply two given Numpy arrays element-wise.
arr17_1=np.arange(12).reshape(4,3)
arr17_2=np.arange(12).reshape(4,3)
print(arr17_1)
print(arr17_2)
print(np.multiply(arr17_1,arr17_2))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[  0   1   4]
 [  9  16  25]
 [ 36  49  64]
 [ 81 100 121]]


In [111]:
# 18. Compute the dot product of two given Numpy arrays.
arr18_1=np.arange(12).reshape(4,3)
arr18_2=np.arange(12).reshape(3,4)
print(arr18_1)
print(arr18_2)
print(np.dot(arr18_1,arr18_2))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 20  23  26  29]
 [ 56  68  80  92]
 [ 92 113 134 155]
 [128 158 188 218]]


In [116]:
# 19. Add a scalar value to a given Numpy array.
arr19=np.arange(10).reshape(5,2)
print(arr19+5)

[[ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]]


In [126]:
# 20. Subtract one Numpy array from another.
arr20_1=np.arange(10).reshape(2,5)
arr20_2=np.arange(10).reshape(2,5)

print(arr20_1 - arr20_2)

[[0 0 0 0 0]
 [0 0 0 0 0]]


In [129]:
# 21. Find the mean, median, and standard deviation of a given Numpy array.
arr21=np.arange(10).reshape(2,5)
print(arr21)
print(np.mean(arr21))
print(np.median(arr21))
print(np.std(arr21))



[[0 1 2 3 4]
 [5 6 7 8 9]]
4.5
4.5
2.8722813232690143


In [137]:
# 22. Sort a given Numpy array along the first axis.
arr22=np.random.randint(1,100,size=10).reshape(5,2)
print(arr22)
sorted_arr = np.sort(arr22, axis=0)
print(sorted_arr)

[[63 23]
 [ 9 26]
 [ 4 89]
 [72 72]
 [67 24]]
[[ 4 23]
 [ 9 24]
 [63 26]
 [67 72]
 [72 89]]


In [141]:
# 23. Find the unique elements of a given Numpy array.
arr23=np.ones((3,3))
unique_elements = np.unique(arr23)
print(unique_elements)

[1.]


In [160]:
# 24. Check if a given Numpy array contains any NaN values.

arr24= np.array([[1, 2], [3, 4], [np.nan, 5]])
print(type(arr24))
has_nan=np.isnan(arr24).any()
print(has_nan)

<class 'numpy.ndarray'>
True


In [167]:
# 25. Create a 5x5 matrix and pad it with zeros along the border.
arr25=np.arange(25).reshape(5, 5)
print(arr25)
pad_arr=np.pad(arr25,pad_width=1,mode='constant',constant_values=0)
print(pad_arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 0  0  0  0  0  0  0]
 [ 0  0  1  2  3  4  0]
 [ 0  5  6  7  8  9  0]
 [ 0 10 11 12 13 14  0]
 [ 0 15 16 17 18 19  0]
 [ 0 20 21 22 23 24  0]
 [ 0  0  0  0  0  0  0]]


In [170]:
# 26. Transpose a given Numpy array.
arr26=np.arange(12).reshape(4, 3)
print(arr26)
print(arr26.T)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [183]:
# 27. Reverse the rows of a given 2D Numpy array.
arr27=np.arange(12).reshape(4, 3)
print(arr27)
reversed_rows = arr27[::-1, :]
print(reversed_rows)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 9 10 11]
 [ 6  7  8]
 [ 3  4  5]
 [ 0  1  2]]


In [185]:
# 28. Compute the cumulative sum of a given Numpy array.
arr27=np.arange(12).reshape(4, 3)
cumsum=np.cumsum(arr27)
print(cumsum)

[ 0  1  3  6 10 15 21 28 36 45 55 66]


In [186]:
# 29. Normalize a given Numpy array.
arr29=np.arange(12).reshape(4, 3)
normalized_arr = (arr29 - np.min(arr29)) / (np.max(arr29) - np.min(arr29))
print(normalized_arr)

[[0.         0.09090909 0.18181818]
 [0.27272727 0.36363636 0.45454545]
 [0.54545455 0.63636364 0.72727273]
 [0.81818182 0.90909091 1.        ]]


In [198]:
#30. Reshape a given Numpy array to have 1 row and multiple columns.
arr30=np.arange(12).reshape(4, 3)
print(arr30)
print(arr30.reshape(1,-1))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11]]
