<a href="https://colab.research.google.com/github/ramesitexp/DataScience_Zone/blob/main/SupportVectorMachine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix


In [2]:
data = {
    'Age': [22, 35, 26, 45, 52, 23, 40, 60, 48, 33],
    'Salary': [25000, 70000, 48000, 90000, 120000, 26000, 85000, 150000, 110000, 60000],
    'Gender': ['Male', 'Female', 'Female', 'Male', 'Male', 'Female', 'Female', 'Male', 'Female', 'Male'],
    'Bought': [0, 1, 0, 1, 1, 0, 1, 1, 1, 1]
}

df = pd.DataFrame(data)


In [4]:
# Encode 'Gender' using Label Encoding
le = LabelEncoder()
df['Gender'] = le.fit_transform(df['Gender'])  # Male = 1, Female = 0

# Features and target
X = df[['Age', 'Salary', 'Gender']]
y = df['Bought']


# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.3, random_state=42)


In [5]:
# Train SVM with RBF kernel
model = SVC(kernel='rbf', C=1.0, gamma='scale')
model.fit(X_train, y_train)

# Predict
y_pred = model.predict(X_test)


In [9]:
X_test

array([[ 0.7863571 ,  0.81687843, -1.        ],
       [-0.27850147, -0.2171449 , -1.        ],
       [-1.26144785, -1.35457056, -1.        ]])

In [8]:
y_test

8    1
1    1
5    0
Name: Bought, dtype: int64

In [7]:
y_pred

array([1, 1, 0])

In [6]:
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))


Confusion Matrix:
[[1 0]
 [0 2]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00         2

    accuracy                           1.00         3
   macro avg       1.00      1.00      1.00         3
weighted avg       1.00      1.00      1.00         3

